### PR TITLE
Better ServerDetection :)

### PR DESCRIPTION
**Pull request by chachyyyy**

### CODE REVIEW

**Comment by asbyth** [comment]
- Hive has several domains, I commonly use `hivemc.eu`, which would break the Hive detection for me.
- What servers are gonna have Hypixel, Mineplex, or HiveMC in their IP?

**Comment by chachyyyy** [comment]
first point i understand
second point idiot servers

**Comment by asbyth** [comment]
they're all copyrighted names, meaning they can be taken down any second once found, not accepting this though due to the nature of it breaking things

**Comment by chachyyyy** [comment]
wow

**Pull request closed without merging**
